import { Footer, Navbar } from '@/components/common'
import '../styles/globals.css'
import type { Metadata } from 'next'
import { Setup } from '@/components/utils'

import 'bootstrap/dist/css/bootstrap.min.css'
import Provider from '@/redux/provider'
import { Router } from 'next/router'



export const metadata: Metadata = {
  title: 'VanguardArt',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Provider>
          <Navbar />
           <Setup />
             <div>{children}</div>
        </Provider>
      </body>
    </html>
  )
}
